name: ${project.name}
version: ${project.version}-${git.commit.id.abbrev}
authors: [Toranktto]
main: pl.toranktto.autoevents.AutoEventsPlugin
depend: [WorldEdit, WorldGuard]
softdepend: [Multiverse-Core, Skript]
api-version: "1.14"
commands:
  event:
    aliases: [autoevent, autoevents]
    usage: /event help
    description: AutoEvents commands.
permissions:
  autoevents.*:
    default: op
    children:
      autoevents.player: true
      autoevents.admin: true
  autoevents.player:
    default: true